CREATE TABLE USERR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(11),
    SECRET_PHRASE VARCHAR(100),
    SECRET_ANSWER VARCHAR(100)
);

CREATE SEQUENCE USERR_SEQ START WITH 1 INCREMENT BY 1;